name: Post-Merge Tests
on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]

jobs:
  pre-merge-tests:
    name: Post-Merge Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13.0]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Run Tests
      run: |
        python3 tests/test_validate_instructions.py

